### ISSUE TITLE
exit() doesn't claim rewards if accountBalance==0.

### ISSUE THREAD

**Issue by ether-bug** [ZeframLou/playpen#4]
https://github.com/ZeframLou/playpen/blob/eef29f32842b59a57958aaa12fef77f614f9e063/src/ERC20StakingPool.sol#L222-L231

Expected behavior for exit() is to claim earned rewards in any case.

However, this doesn't happen if accountBalance==0. This can happen if user withdraws their stake without claiming their rewards, leaving pending rewards.

**Comment by ZeframLou** [comment]
Nice catch!

**Comment by SvenMeyer** [comment]
I think we have the same issue in https://github.com/ZeframLou/playpen/blob/main/src/ERC721StakingPool.sol
Line 226
