### ISSUE TITLE
Version without xERC20

### ISSUE THREAD

**Issue by daweth** [ZeframLou/playpen#5]
Instead of storing staked amounts as tokens, some projects would benefit from a version without the additional contract. I propose a duplicate set of contracts implemented without the existence of a staking reward token.

Since it's a simple fork I'm asking the author if they think this should be part of the repo @ZeframLou

**Comment by daweth** [comment]
It's possible to implement StakingPoolFactory.sol with the zero address as xERC20 but this results in nonfunctional code. (createxERC20 can't be used)

**Comment by ZeframLou** [comment]
It doesn't seem necessary, since once the factory is deployed on a chain it doesn't need to be deployed ever again, so having as many features as possible is the way to go. Thanks for the suggestion though!
